accounts/urls.py
from django.urls import path, include

from .views import (
    ProfileDetailView,
    ProfileUpdateView,
    SignupCreateView,
)


app_name = 'accounts'

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('profile/<pk>/',ProfileDetailView.as_view(), name = 'profile-detail'),
    path('profile/<pk>/update/',ProfileUpdateView.as_view(), name = 'profile-update'),
    path('signup/', SignupCreateView.as_view(), name="signup"),
    
]

dashboard/urls.py
from django.urls import path, include
from. views import DashboardView

app_name ='dashboard'

urlpatterns = [
    path('',DashboardView.as_view(), name='dashboard'),
]

social_analytics/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required, permission_required

urlpatterns = [
    path('', include('dashboard.urls'), name='dashboard'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls'), name = 'accounts'),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.contrib.auth.models import User, Group
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django_countries.fields import CountryField
from phonenumber_field.modelfields import PhoneNumberField
from social_analytics import settings
from django.urls import reverse
from guardian.shortcuts import assign_perm

class Profile(models.Model):
    user                    =       models.OneToOneField(User, on_delete=models.CASCADE)
    full_name               =       models.CharField(max_length=100)
    address1                =       models.CharField(verbose_name='Street address', max_length=150,null=True, blank=True)
    address2                =       models.CharField(verbose_name='Address 2', max_length=150, blank=True, null=True)
    locality                =       models.CharField(verbose_name='City/Town', max_length=50, null=True, blank=True)
    region                  =       models.CharField(verbose_name='State/Province/County', max_length=50, null=True, blank=True)
    postal_code             =       models.CharField(verbose_name='Zip/Postal code', max_length=50, null=True, blank=True)
    country                 =       CountryField('Country', null=True, blank=True)
    phone_number            =       PhoneNumberField(null=True, blank=True)
    email                   =       models.EmailField(null=True, blank=True)
    image                   =       models.ImageField(upload_to='profile_pics',blank=True, null=True)
    created_on              =       models.DateTimeField(auto_now_add=True)
    modified_on             =       models.DateTimeField(auto_now=True)

    class Meta:
        default_permissions = ('add', 'change', 'delete')
        permissions = (
            ('view_profile', 'Can view profile'),
        )

    def __str__(self): 
        return self.user.username
    
    def get_absolute_url(self):
        return reverse("accounts:profile-detail", kwargs={"pk": self.pk})
    
    @property
    def profile_picture(self):
        if self.image:
            return self.image.url
        else:
            return '/static/profile_pics/profile_pic_placeholder.png'
    
    
        

@receiver(post_save, sender=User)
def create_or_update_user_profile(sender, instance, created, **kwargs):
    
    if created and instance.username != settings.ANONYMOUS_USER_NAME:
        profile = Profile.objects.create(pk=instance.pk, user=instance)
        assign_perm("change_user", instance, instance)
        assign_perm('view_profile', instance, profile)
        assign_perm('change_profile', instance, profile)
        assign_perm('delete_profile', instance, profile)
    try:
        instance.profile.save()
    except Exception as e:
        print(e)

dashboard/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms
from .models import Profile
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class ProfileForm(forms.ModelForm):
    class Meta:
        model   =   Profile
        fields  =   [
            'full_name',
            'address1',
            'address2',
            'locality',
            'region',
            'postal_code',
            'country',
            'phone_number',
            'email',
            'image'
        ]



class SignUpForm(UserCreationForm):
    username = forms.EmailField(max_length=200)

    class Meta:
        model = User
        fields = ('username', 'password1', 'password2', )

accounts/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib.auth import login, authenticate
from django.views.generic import DetailView, UpdateView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from guardian.mixins import PermissionRequiredMixin, PermissionListMixin
from .models import Profile
from .forms import ProfileForm, SignUpForm


class ProfileDetailView(LoginRequiredMixin, DetailView):
    model       =       Profile
    template_name = 'accounts/profile_detail.html'

class ProfileUpdateView(PermissionRequiredMixin, UpdateView):
    model       =       Profile
    form_class  =       ProfileForm
    permission_required = ['view_profile', 'change_profile']
    template_name   =   'base/snippets/forms/create_update.html'


class SignupCreateView(CreateView):
    form_class      =   SignUpForm
    template_name   =   'accounts/signup.html'
    def form_valid(self, form):
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            login(self.request, user)
            user_id = user.id
            return redirect(reverse('accounts:profile-update', args= { user_id}))
        return render(self.request, reverse('accounts:signup'), {'form': form})    

dashboard/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic.base import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin

class DashboardView(LoginRequiredMixin, TemplateView):
    template_name = "dashboard.html"

    # def get_context_data(self, **kwargs):
    #     context                     =   super(DashboardView, self).get_context_data(**kwargs)
    #     context['unposted_income']  =   IncomeJournal.objects.aggregate(Sum('amount'))
    #     context['unposted_expense'] =   ExpenseJournal.objects.aggregate(Sum('amount'))
    #     context['posted_income']    =   PostedIncome.objects.aggregate(Sum('amount'))
    #     context['posted_expense']   =   PostedExpense.objects.aggregate(Sum('amount'))                
    #     return context

templates/accounts/profile_detail.html
{% extends 'base.html' %} 
{% load static %}
{% block content %}

    <div class="container-fluid mt-2">
      <div class="row">
        <div class="col-xl-8 order-xl-1 mx-auto">
          <div class="card card-profile shadow">
            <div class="row justify-content-center">
              <div class="col-lg-3 order-lg-2">
                <div class="card-profile-image">
                  <a href="#">
                    <img src="{{object.profile_picture}}" class="rounded-circle">
                  </a>
                </div>
              </div>
            </div>
            <div class="card-header text-center border-0 pt-8 pt-md-4 pb-0 pb-md-4">
              <div class="d-flex justify-content-between">
                <a href="#" class="btn btn-sm btn-info mr-4">Connect</a>
                <a href="{% url 'accounts:profile-update' object.pk %} " class="btn btn-sm btn-default float-right">edit</a>
              </div>
            </div>
            <div class="card-body pt-0 pt-md-4">
              <div class="row">
                <div class="col">
                  <div class="card-profile-stats d-flex justify-content-center mt-md-5">
                    <div>
                      <span class="heading">email</span>
                      <span class="description">{% if object.email %}{{ object.email}}{% endif %}</span>
                    </div>
                    <div>
                      <span class="heading">Phone</span>
                      <span class="description">{% if object.phone_number %}{{ object.phone_number}}{% endif %}</span>
                    </div>

                  </div>
                </div>
              </div>
              <div class="text-center">
                <h3>
                  {{ object.full_name}}<span class="font-weight-light">, 27</span>
                </h3>
                <div class="h5 font-weight-300">
                  <i class="ni location_pin mr-2"></i>
                  {% if object.address1 %}{{ object.address1}}{% endif %}
                  {% if object.address2 %}, {{ object.address2}}{% endif %}
                  {% if object.locality %}, {{ object.locality}}{% endif %}
                  {% if object.region %}, {{ object.region}}{% endif %}
                  {% if object.postal_code %}, {{ object.postal_code}}{% endif %}
                  {% if object.country %}, {{ object.country}}{% endif %}
                </div>
                <div class="h5 mt-4">
                  <i class="ni business_briefcase-24 mr-2"></i>{% if object.occupation %}{{ object.occupation}}{% endif %} {% if object.organisation %}  {{ object.organisation}}{% endif %}
                </div>
                <hr class="my-4" />
                <p>
                  {% if object.about_me %} {{ object.about_me}}{% endif %}
                </p>

              </div>
            </div>
          </div>
        </div>


        </div>
        </div>

{% endblock content %}

templates/accounts/signup.html
{% extends 'registration/auth_base.html' %}
{% block auth %}
  <div class="row justify-content-center">
      <div class="col-lg-5 col-md-7">
          <div class="card bg-secondary shadow border-0">
              <div class="card-body px-lg-5 py-lg-5">
                  <div class="text-center text-muted mb-4">
                      <small>Create an Account</small>
                  </div>
                  <div>
<h2>Sign up Form</h2>
            <form method="post">
            {% csrf_token %}
            {% for field in form %}
                <p>
                {{ field.label_tag }}<br>
                {{ field }}
                {% if field.help_text %}
                    <small style="color: grey">{{ field.help_text }}</small>
                {% endif %}
                {% for error in field.errors %}
                    <p style="color: red">{{ error }}</p>
                {% endfor %}
                </p>
            {% endfor %}
            <button type="submit">Sign up</button>
            </form>

                  </div>
              </div>
          </div>
      </div>
{% endblock auth %}

templates/base.html
<!--

=========================================================
* Argon Dashboard - v1.1.1
=========================================================

* Product Page: https://www.creative-tim.com/product/argon-dashboard
* Copyright 2019 Creative Tim (https://www.creative-tim.com)
* Licensed under MIT (https://github.com/creativetimofficial/argon-dashboard/blob/master/LICENSE.md)

* Coded by Creative Tim

=========================================================

* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software. -->

{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title >
    Thooni
  </title>
  <!-- Favicon-->
  <link href=" {% static 'assets/img/brand/favicon.png' %}" rel="icon" type="image/png">  
  <!-- Fonts -->
  {% include 'base/fonts.html' %}
  <!-- Icons -->
  {% include 'base/icons.html' %}
  <!-- CSS Files -->
  {% include 'base/css.html' %}
  
</head>

<body class="">
  <nav class="navbar navbar-vertical fixed-left navbar-expand-md navbar-light bg-white" id="sidenav-main">
    <div class="container-fluid">
      <!-- Toggler -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#sidenav-collapse-main" aria-controls="sidenav-main" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <!-- Brand 
      <a class="navbar-brand pt-0" href="{% url 'dashboard:dashboard'%}">
        <span class="text-primary">         <img src="{% static 'assets/img/brand/logo.png' %}"> </span>
      </a> -->
      <h1 style="font-family:'Montserrat', sans-serif;color: #5473E8;">
        <a href="{% url 'dashboard:dashboard'%}">bluedoor.io</a>
      </h1>      
      <!-- Collapsed User Profile-->
        {% include 'base/collapsed/user_profile.html' %}

      <!-- Collapse -->
      <div class="collapse navbar-collapse" id="sidenav-collapse-main">
        <!-- Collapse header -->
      {% include 'base/collapsed/header.html' %}
        <!-- Collapsed Search -->
      {% include 'base/collapsed/search.html' %}

        <!-- Collapsed NAV -->
      {% include 'base/collapsed/nav.html' %}



  <div class="main-content">
    <!-- Navbar -->
    <nav class="navbar navbar-top navbar-expand-md navbar-dark" id="navbar-main">
      <div class="container-fluid">
        <!-- Brand -->
        <a class="h4 mb-0 text-white text-uppercase d-none d-lg-inline-block"> 
        {% block app_name %}
        {% endblock app_name %}
        </a>
        <!-- Form -->
        {% include 'base/main/search.html' %}
        <!-- User -->
        {% include 'base/main/user_profile.html' %}
      </div>
    </nav>
    <!-- End Navbar -->
    <!-- Header -->
    <div class="header bg-gradient-primary pt-5 pt-md-8">
          {% block header %}{% endblock header %}


    </div>

          <div class="container-fluid mt-5">



        <!-- Block Contents -->

          {% block content %}{% endblock content %}
        <!-- End Contents -->

      </div>
  </div>

<!--   Java script    -->
{% include 'base/js.html' %}
{% include 'base/snippets/forms/js/loqate.html' %}

</body>

</html>

templates/base/calendar.html
        <!-- Favicon -->




  <!-- Page plugins -->
  <link rel="stylesheet" href="https://demos.creative-tim.com/argon-dashboard-pro/assets/vendor/fullcalendar/dist/fullcalendar.min.css">
  <link rel="stylesheet" href="https://demos.creative-tim.com/argon-dashboard-pro/assets/vendor/sweetalert2/dist/sweetalert2.min.css">
  <!-- Argon CSS -->

  <!-- Google Tag Manager -->

      
      <div class="row">
        <div class="col">
          <!-- Fullcalendar -->
          <div class="card card-calendar">
            <!-- Card header -->
            <div class="card-header">
              <!-- Title -->
              <h5 class="h3 mb-0">Calendar</h5>
            </div>
            <!-- Card body -->
            <div class="card-body p-0">
              <div class="calendar" data-toggle="calendar" id="calendar"></div>
            </div>
          </div>
          <!-- Modal - Add new event -->
          <!--* Modal header *-->
          <!--* Modal body *-->
          <!--* Modal footer *-->
          <!--* Modal init *-->
          <div class="modal fade" id="new-event" tabindex="-1" role="dialog" aria-labelledby="new-event-label" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered modal-secondary" role="document">
              <div class="modal-content">
                <!-- Modal body -->
                <div class="modal-body">
                  <form class="new-event--form">
                    <div class="form-group">
                      <label class="form-control-label">Event title</label>
                      <input type="text" class="form-control form-control-alternative new-event--title" placeholder="Event Title">
                    </div>
                    <div class="form-group mb-0">
                      <label class="form-control-label d-block mb-3">Status color</label>
                      <div class="btn-group btn-group-toggle btn-group-colors event-tag" data-toggle="buttons">
                        <label class="btn bg-info active"><input type="radio" name="event-tag" value="bg-info" autocomplete="off" checked></label>
                        <label class="btn bg-warning"><input type="radio" name="event-tag" value="bg-warning" autocomplete="off"></label>
                        <label class="btn bg-danger"><input type="radio" name="event-tag" value="bg-danger" autocomplete="off"></label>
                        <label class="btn bg-success"><input type="radio" name="event-tag" value="bg-success" autocomplete="off"></label>
                        <label class="btn bg-default"><input type="radio" name="event-tag" value="bg-default" autocomplete="off"></label>
                        <label class="btn bg-primary"><input type="radio" name="event-tag" value="bg-primary" autocomplete="off"></label>
                      </div>
                    </div>
                    <input type="hidden" class="new-event--start" />
                    <input type="hidden" class="new-event--end" />
                  </form>
                </div>
                <!-- Modal footer -->
                <div class="modal-footer">
                  <button type="submit" class="btn btn-primary new-event--add">Add event</button>
                  <button type="button" class="btn btn-link ml-auto" data-dismiss="modal">Close</button>
                </div>
              </div>
            </div>
          </div>
          <!-- Modal - Edit event -->
          <!--* Modal body *-->
          <!--* Modal footer *-->
          <!--* Modal init *-->
          <div class="modal fade" id="edit-event" tabindex="-1" role="dialog" aria-labelledby="edit-event-label" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered modal-secondary" role="document">
              <div class="modal-content">
                <!-- Modal body -->
                <div class="modal-body">
                  <form class="edit-event--form">
                    <div class="form-group">
                      <label class="form-control-label">Event title</label>
                      <input type="text" class="form-control form-control-alternative edit-event--title" placeholder="Event Title">
                    </div>
                    <div class="form-group">
                      <label class="form-control-label d-block mb-3">Status color</label>
                      <div class="btn-group btn-group-toggle btn-group-colors event-tag mb-0" data-toggle="buttons">
                        <label class="btn bg-info active"><input type="radio" name="event-tag" value="bg-info" autocomplete="off" checked></label>
                        <label class="btn bg-warning"><input type="radio" name="event-tag" value="bg-warning" autocomplete="off"></label>
                        <label class="btn bg-danger"><input type="radio" name="event-tag" value="bg-danger" autocomplete="off"></label>
                        <label class="btn bg-success"><input type="radio" name="event-tag" value="bg-success" autocomplete="off"></label>
                        <label class="btn bg-default"><input type="radio" name="event-tag" value="bg-default" autocomplete="off"></label>
                        <label class="btn bg-primary"><input type="radio" name="event-tag" value="bg-primary" autocomplete="off"></label>
                      </div>
                    </div>
                    <div class="form-group">
                      <label class="form-control-label">Description</label>
                      <textarea class="form-control form-control-alternative edit-event--description textarea-autosize" placeholder="Event Desctiption"></textarea>
                      <i class="form-group--bar"></i>
                    </div>
                    <input type="hidden" class="edit-event--id">
                  </form>
                </div>
                <!-- Modal footer -->
                <div class="modal-footer">
                  <button class="btn btn-primary" data-calendar="update">Update</button>
                  <button class="btn btn-danger" data-calendar="delete">Delete</button>
                  <button class="btn btn-link ml-auto" data-dismiss="modal">Close</button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

    </div>
  </div>
  <!-- Argon Scripts -->
  <!-- Core -->
  <script src="https://demos.creative-tim.com/argon-dashboard-pro/assets/vendor/jquery/dist/jquery.min.js"></script>
  <script src="https://demos.creative-tim.com/argon-dashboard-pro/assets/vendor/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
  <script src="https://demos.creative-tim.com/argon-dashboard-pro/assets/vendor/js-cookie/js.cookie.js"></script>
  <script src="https://demos.creative-tim.com/argon-dashboard-pro/assets/vendor/jquery.scrollbar/jquery.scrollbar.min.js"></script>
  <script src="https://demos.creative-tim.com/argon-dashboard-pro/assets/vendor/jquery-scroll-lock/dist/jquery-scrollLock.min.js"></script>
  <!-- Optional JS -->
  <script src="https://demos.creative-tim.com/argon-dashboard-pro/assets/vendor/moment/min/moment.min.js"></script>
  <script src="https://demos.creative-tim.com/argon-dashboard-pro/assets/vendor/fullcalendar/dist/fullcalendar.min.js"></script>
  <script src="https://demos.creative-tim.com/argon-dashboard-pro/assets/vendor/sweetalert2/dist/sweetalert2.min.js"></script>
  <!-- Argon JS -->
  <script src="https://demos.creative-tim.com/argon-dashboard-pro/assets/js/argon.min.js?v=1.2.0"></script>

templates/base/collapsed/header.html
{% load static %}
<div class="navbar-collapse-header d-md-none">
    <div class="row">
    <div class="col-6 collapse-brand">
        <a href="./index.html">
        <img src="{% static 'assets/img/brand/logo.png' %}">
        </a>
    </div>
    <div class="col-6 collapse-close">
        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#sidenav-collapse-main" aria-controls="sidenav-main" aria-expanded="false" aria-label="Toggle sidenav">
        <span></span>
        <span></span>
        </button>
    </div>
    </div>
</div>

templates/base/collapsed/nav.html
{% load static %}
<ul class="navbar-nav">
    <li class="nav-item  active ">
        <a class="nav-link  active " href="{% url 'dashboard:dashboard'%}">
            <i class="ni ni-tv-2 text-primary"></i> Dashboard
        </a>
    </li>

    <li class="nav-item">
        <a class="nav-link " href="">
            <i class="fas fa-user-friends text-blue"></i> Leads
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link " href="">
            <i class="fas fa-users text-grey"></i> Accounts
        </a>
    </li>
        <a class="nav-link " href="#social_media" data-toggle="collapse" role="button" aria-expanded="false" aria-controls="social_media">
        <i class="fas fa-hashtag text-info"></i>
        <span class="nav-link-text">Socaial Media</span>
    </a>
        <div class="collapse" id="social_media">
            <ul class="nav nav-sm flex-column">

                <li class="nav-item">
                    <a class="nav-link " href="">
                        <i class="fas fa-instagram text-purple"></i> Instagram
                    </a>
                </li>
            
                <li class="nav-item">
                    <a class="nav-link " href="">
                        <i class="fas fa-facebook text-blue"></i> Facebook
                    </a>
                </li>            

                <li class="nav-item">
                    <a class="nav-link " href="">
                        <i class="fas fa-twitter text-blue"></i> Twitter
                    </a>
                </li>

                <li class="nav-item">
                    <a class="nav-link " href="">
                        <i class="fas fa-tiktok text-DarkTurquoise"></i> Tiktok
                    </a>
                </li>

                <li class="nav-item">
                    <a class="nav-link " href="">
                        <i class="fas fa-youtube text-red"></i> Youtube
                    </a>
                </li>
            </ul>
        </div>
</ul>






    </div>
    </div>
    </nav>

templates/base/collapsed/search.html
<form class="mt-4 mb-3 d-md-none">
    <div class="input-group input-group-rounded input-group-merge">
    <input type="search" class="form-control form-control-rounded form-control-prepended" placeholder="Search" aria-label="Search">
    <div class="input-group-prepend">
        <div class="input-group-text">
        <span class="fa fa-search"></span>
        </div>
    </div>
    </div>
</form>

templates/base/collapsed/user_profile.html
{% load static %}
<!-- User -->

<ul class="nav align-items-center d-md-none">
  <li class="nav-item dropdown">
    <a class="nav-link nav-link-icon" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <i class="ni ni-bell-55"></i>
    </a>
    <div class="dropdown-menu dropdown-menu-arrow dropdown-menu-right" aria-labelledby="navbar-default_dropdown_1">
      <a class="dropdown-item" href="#">Action</a>
      <a class="dropdown-item" href="#">Another action</a>
      <div class="dropdown-divider"></div>
      <a class="dropdown-item" href="#">Something else here</a>
    </div>
  </li>
  <li class="nav-item dropdown">
    <a class="nav-link" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <div class="media align-items-center">
        <span class="avatar avatar-sm rounded-circle">
          <img alt="Image placeholder" src=" {{request.user.profile.profile_picture}}">
        </span>
      </div>
    </a>
    <div class="dropdown-menu dropdown-menu-arrow dropdown-menu-right">
      <div class=" dropdown-header noti-title">
        <h6 class="text-overflow m-0">{{request.user.profile.full_name}}</h6>
      </div>
      
      <a href="{% if user.is_authenticated %}{% url 'accounts:profile-detail' user.id %}{% endif %}" class="dropdown-item">
        <i class="ni ni-single-02"></i>
        <span>My profile</span>
      </a>
      <a href="./examples/profile.html" class="dropdown-item">
        <i class="ni ni-settings-gear-65"></i>
        <span>Settings</span>
      </a>
      <a href="./examples/profile.html" class="dropdown-item">
        <i class="ni ni-calendar-grid-58"></i>
        <span>Activity</span>
      </a>
      <a href="./examples/profile.html" class="dropdown-item">
        <i class="ni ni-support-16"></i>
        <span>Support</span>
      </a>
      {% if user.is_authenticated %}
        <div class="dropdown-divider"></div>
        <a href="{% url 'accounts:logout'%}?next={{request.path}}" class="dropdown-item">
          <i class="ni ni-user-run"></i>
          <span>Logout</span>
      {% endif %}  
      </a>
    </div>
  </li>
</ul>

templates/base/css.html
{% load static %}
<link href="{% static 'assets/css/argon-dashboard.css' %}" rel="stylesheet" />

templates/base/fonts.html
<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">

templates/base/icons.html
{% load static %}
<link href=" {% static 'assets/js/plugins/nucleo/css/nucleo.css' %}" rel="stylesheet" />
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.css" rel="stylesheet" />

templates/base/js.html
  {% load static %}
  
  <!--   Core   -->
  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"></script>
  <!--   Optional JS   -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.bundle.min.js"></script>
  <script src="{% static 'assets/js/plugins/chart.js/dist/Chart.extension.js' %}"></script>
  <!--   Argon JS   -->
  <script src="{% static 'assets/js/argon-dashboard.min.js' %}"></script>
<!--
<script src="https://cdn.trackjs.com/agent/v3/latest/t.js"></script>


<script src="https://code.tidio.co/titn6sfl0jay4cveu3neb88gbpklxpay.js" async>     -->
</script>

templates/base/main/footer.html
<!-- Footer -->
<footer class="footer">
    <div class="row align-items-center justify-content-xl-between">
        <div class="col-xl-6">
        </div>
        <div class="col-xl-6">
        <ul class="nav nav-footer justify-content-center justify-content-xl-end">
        </ul>
        </div>
    </div>
</footer>

templates/base/main/search.html
<form class="navbar-search navbar-search-dark form-inline mr-3 d-none d-md-flex ml-lg-auto"  action='' >
    <div class="form-group mb-0">
    <div class="input-group input-group-alternative">
        <div class="input-group-prepend">
        <span class="input-group-text"><i class="fas fa-search"></i></span>
        </div>
        <input class="form-control" placeholder="Search" type="text" name='q' aria-label="Search" value='{{ request.GET.q }}' />
    </div>
    </div>
    <div>
    <ul class="list-group" id="result"></ul>
    </div>
</form>

templates/base/snippets/forms/js/loqate.html
<script>(function(n,t,i,r){var u,f;n[i]=n[i]||{},n[i].initial={accountCode:"DWELL11113",host:"DWELL11113.pcapredict.com"},n[i].on=n[i].on||function(){(n[i].onq=n[i].onq||[]).push(arguments)},u=t.createElement("script"),u.async=!0,u.src=r,f=t.getElementsByTagName("script")[0],f.parentNode.insertBefore(u,f)})(window,document,"pca","//DWELL11113.pcapredict.com/js/sensor.js")</script>

templates/homepage.html
/Users/sreejithmuralidharan/Documents/Dev/Dwelling Condos/env/src/dwelling_condos/templates/homepage.html
/Users/sreejithmuralidharan/Documents/Dev/Dwelling Condos/env/src/templates/homepage.html
/Users/sreejithmuralidharan/Documents/Dev/Dwelling Condos/env/src/dwelling_condos/templates/homepage.html